"""empty message

Revision ID: 1a5b4d9671d1
Revises: decee2420d35
Create Date: 2025-07-03 14:42:27.536825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5b4d9671d1'
down_revision = 'decee2420d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_game_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_user_game_library'), type_='unique')
        batch_op.create_unique_constraint('unique_user_steam_game_library', ['user_id', 'steam_game_id'])
        batch_op.drop_constraint(batch_op.f('user_library_game_id_fkey'), type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('user_library_game_id_fkey'), 'games', ['game_id'], ['id'])
        batch_op.drop_constraint('unique_user_steam_game_library', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_user_game_library'), ['user_id', 'game_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('steam_game_id')

    # ### end Alembic commands ###
